Pop up
Sofinaye/Portfolio pull request #10
Opened 2023-02-10 23:27 UTC by Sofinaye

I add the popup window functionality to the project part.

2023-02-10 23:33 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @Sofinaye , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a project, that has non descriptive PR summary and lacks commits from your partner

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-11 09:50 UTC, FrederickMih requested changes
## Hi 🙋 @Sofinaye  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)


## Highlights <img src = "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif" width='30' ></img>


- PR is professional ✔️ 
- Linters checks passed ✔️


## Required Changes ♻️

- [ ] As stated in the requirements let's kindly make sure the [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) linter is equally set up in this project repo.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 09:50 UTC, FrederickMih commented on index.js
> +  },
- [ ] Let's kindly make sure the design of our popup strictly follows that of Figma(e.g., font, colors, images, text, margins). Let's check out the two screenshots below and make the necessary adjustments. See live, see source, technologies buttons are not showing up. Let the popup be populated with all the data from the project array. Please kindly fix the issues.

| Yours | Figma |
| --- | --- |
| ![yourpopup](https://user-images.githubusercontent.com/63087491/218251336-bf6d7850-06c8-41c9-a99c-83ce57eb4c75.PNG) | ![Capture](https://user-images.githubusercontent.com/63087491/218251343-7ea118a0-67e8-4635-a36f-353510059e2d.PNG) |

- [ ] Also, kindly check and compare your mobile design to that of Figma.

2023-02-11 20:16 UTC, huseyinbiyik requested changes
Hi team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 20:16 UTC, huseyinbiyik commented on style.css
> +.popup-disc-btn {
As the previous reviewer requested, stick to the Figma template, decrease the size of popup and align buttons like below.
<img width="743" alt="Screenshot 2023-02-11 at 11 02 08 PM" src="https://user-images.githubusercontent.com/25887253/218279094-e7571eac-d521-4348-985e-25d12d0e69c7.png">
<img width="1208" alt="Screenshot 2023-02-11 at 11 00 17 PM" src="https://user-images.githubusercontent.com/25887253/218279089-a5f2d174-8134-46d2-8a97-8dc2ed6db97a.png">

2023-02-11 20:16 UTC, huseyinbiyik commented on style.css
> +  .popupBody {
Kindly stick to the Figma template as the previous reviewer requested and fix the overflowing issue and add some space above buttons.
![Screen Recording 2023-02-11 at 11 06 54 PM](https://user-images.githubusercontent.com/25887253/218279217-dc833176-7a51-4fcd-9829-fa1b93bc3f89.gif)

2023-02-11 20:16 UTC, huseyinbiyik commented on index.html
> -          <li><button type="button" class="project1-btns">html</button></li>
As the previous reviewer requested please stick to the design provided and make sure all popups are working properly.

![Screen Recording 2023-02-11 at 11 03 58 PM](https://user-images.githubusercontent.com/25887253/218279318-fc476e92-16d7-4518-9e4a-e0b7d402eae2.gif)

2023-02-11 22:29 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @Sofinaye , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-11 22:29 UTC, bobb-Rob commented on index.js
> +    popup.setAttribute('class', 'popup');
- [ ] As mentioned by the previous reviewer, the popup is not properly displaying. Currently it is not scrollable to enable users to see the text and button hidden down.

![image](https://user-images.githubusercontent.com/84156714/218283693-16dd6cd7-cf10-4c12-aea3-fdac3bd0b85c.png)

I suggest you add the overflow- [See tutorial](https://www.w3schools.com/css/css_overflow.asp) on how to do this.

The desktop view hides the popup heading
![image](https://user-images.githubusercontent.com/84156714/218283746-caebe567-d5dc-49fe-95bb-f558965ceafc.png)


Please fix this

2023-02-11 23:12 UTC, MahmoudBakr23 approved these changes
Hi @Sofinaye 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Great work and effort on making the requested changes from the previous reviewers and on the design overall 💯 

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-13 21:44 UTC, merged