Toggle menu
Sofinaye/Portfolio pull request #8
Opened 2023-02-07 13:28 UTC by Sofinaye

I added the menu list 

-  and a javascript file that makes the menu list appear when you click the hamburger

- and to disappear when the X button is clicked.

2023-02-07 13:44 UTC, ichala requested changes
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linter errors  ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑 As Part of the requirements , kindly add the [JAVASCRIPT ](https://github.com/microverseinc/linters-config/tree/master/javascript) LINTERS TO YOUR REPO AS WELL 🙏_**
- [ ] **_🛑  Check The Comments Below_**





## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 13:44 UTC, ichala commented on index.html
> +          <li class="menu-item"><a href="#contact">Contact</a></li>
- [ ] when I open the mobile menu and click a link to a section, there's a bug preventing me from scrolling or clicking anywhere, kindly fix that 🙏 


![bug](https://user-images.githubusercontent.com/89282221/217259971-98d51b8b-ab67-40ee-8528-949278dd7b12.gif)

2023-02-07 13:44 UTC, ichala commented on index.html
> +        </ul>
- [ ] as part of the requirements the mobile menu should only be visible in the mobile view , kindly fix the issue where it stays visible for large screens 🙏 

![fxxxxxxx](https://user-images.githubusercontent.com/89282221/217260607-9359a8dc-8af9-4f37-b768-139115fcc7c2.gif)

2023-02-07 13:44 UTC, ichala commented on index.html
> +          <button id="menu-toggle" class="menu-toggle"><i class="fa-solid fa-xmark"></i></button>
- [ ] kindly increase the size of the "**X**" button and change its color to match the Figma design 

![image](https://user-images.githubusercontent.com/89282221/217261050-c484793e-cc6c-411f-80b5-39236624c81c.png)

2023-02-08 01:51 UTC, emmiiorji approved these changes
Hi @Sofinaye, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![CongratulationsGifkaroGIF](https://user-images.githubusercontent.com/20554583/216782757-b4063a2b-4168-4b3e-bfda-21af39d0191e.gif)


## Good Highlights✔️

- Requested changes have been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 06:52 UTC, Sofinaye commented
An expandable menu for mobile version

2023-02-08 06:52 UTC, merged